# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming_shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='Port_ETA',
            field=models.CharField(max_length=8, verbose_name='Port ETA'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='Store_ETA',
            field=models.CharField(max_length=8, verbose_name='Into Store ETA'),
        ),
    ]
