# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('WH', models.CharField(max_length=3)),
                ('User', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(verbose_name='date entered')),
            ],
        ),
    ]
