# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0003_auto_20170815_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shipments',
        ),
    ]
