# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0004_delete_shipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='OTP',
            field=models.CharField(choices=[('AIR', 'AIR'), ('SEA', 'SEA'), ('LOC', 'LOC')], default='AIR', max_length=3),
        ),
    ]
