# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0006_auto_20170907_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='User',
        ),
    ]
