# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_requests', '0008_auto_20180410_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='User',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
