# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0011_auto_20180410_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='User',
        ),
    ]
