# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ennery_ConfirmPOLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=8, verbose_name='invoice')),
                ('part', models.CharField(max_length=30, verbose_name='part')),
                ('qty', models.IntegerField(max_length=8, verbose_name='qty')),
                ('value', models.FloatField(max_length=8, verbose_name='value')),
                ('po', models.CharField(max_length=20, verbose_name='po')),
                ('eta', models.CharField(max_length=8, verbose_name='eta')),
                ('tlv', models.CharField(max_length=8, verbose_name='tlv')),
            ],
        ),
    ]
