# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ennery_confirmpolines',
            name='qty',
            field=models.IntegerField(verbose_name='qty'),
        ),
    ]
