# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_auto_20180410_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ennery_confirmpolines',
            name='tlv',
            field=models.CharField(max_length=20, verbose_name='tlv'),
        ),
    ]
