# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0003_auto_20180411_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sparex_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connection', models.CharField(max_length=9, verbose_name='connection')),
                ('part', models.CharField(max_length=30, verbose_name='part')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('value', models.FloatField(max_length=8, verbose_name='value')),
                ('po', models.CharField(max_length=20, verbose_name='po')),
                ('eta', models.CharField(max_length=8, verbose_name='eta')),
                ('line', models.IntegerField(verbose_name='line')),
                ('invoice', models.CharField(max_length=5, verbose_name='invoice')),
                ('tlv', models.CharField(max_length=20, verbose_name='tlv')),
            ],
        ),
    ]
