# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0004_sparex_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparex_invoice',
            old_name='Connection',
            new_name='connection',
        ),
        migrations.RemoveField(
            model_name='sparex_invoice',
            name='line',
        ),
    ]
