# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0005_auto_20180413_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparex_invoice',
            name='connection',
            field=models.CharField(max_length=10, verbose_name='connection'),
        ),
        migrations.AlterField(
            model_name='sparex_invoice',
            name='eta',
            field=models.CharField(max_length=30, verbose_name='eta'),
        ),
        migrations.AlterField(
            model_name='sparex_invoice',
            name='invoice',
            field=models.CharField(max_length=30, verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='sparex_invoice',
            name='value',
            field=models.FloatField(max_length=30, verbose_name='value'),
        ),
    ]
