# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0006_auto_20180413_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparex_invoice',
            name='tlv',
        ),
    ]
